[package]
name = "packet_sniffer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pnet = "0.35.0"
serde = {version = "1.0.125", features = ["derive"]}
serde_json = {version = "1.0.125"}